// WanderAI Hidden Gems Database — 全国 23 城，80+ 隐藏宝藏地点
// 每城市 3-5 个地点，重点挖掘老街区、独立书店、文艺咖啡馆、历史街区、非遗体验馆、小众博物馆、街头艺术区

export interface GemSpot {
  id: string;
  name: string;
  city: string;
  region: string;
  lat: number;
  lng: number;
  description: string;
  reason: string;
  bestTime: string;
  estimatedTime: string;
  cost: string;
  nearbySpots: string[];
  tags: string[];
  imageUrl: string;
  imageColor: string;
}

export const allHiddenGems: GemSpot[] = [
  // ==================== 华东 · 杭州 ====================
  {
    id: "hg-hz-1", name: "小河直街", city: "杭州", region: "华东",
    lat: 30.324, lng: 120.137,
    description: "运河边保留最完整的历史街区，白墙黛瓦，水道纵横，藏着十几家独立咖啡馆。",
    reason: "游客稀少，能体验真正的老杭州生活，随手一拍都是电影感。",
    bestTime: "下午 2:00-6:00", estimatedTime: "2-3小时", cost: "免费（咖啡 ¥30-50）",
    nearbySpots: ["桥西历史街区", "运河天地", "大兜路"],
    tags: ["City Walk", "咖啡馆", "摄影", "古建筑"],
    imageUrl: "https://picsum.photos/800/600?random=41",
    imageColor: "#8BA888",
  },
  {
    id: "hg-hz-2", name: "法喜寺旁茶园小径", city: "杭州", region: "华东",
    lat: 30.238, lng: 120.116,
    description: "法喜寺东侧一条鲜有人知的山径，通往一片秘境茶园，运气好能看到云海。",
    reason: "游客挤在灵隐寺，这条路才是本地人的秘密花园。",
    bestTime: "清晨 6:00-9:00", estimatedTime: "1.5-2小时", cost: "免费",
    nearbySpots: ["法喜寺", "灵隐寺", "中天竺"],
    tags: ["自然风光", "摄影", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=42",
    imageColor: "#5B8C5A",
  },
  {
    id: "hg-hz-3", name: "馒头山社区", city: "杭州", region: "华东",
    lat: 30.245, lng: 120.168,
    description: "老杭州最后的市井生活样本，歪歪扭扭的巷子、晾衣杆、杂货铺，影视剧取景地。",
    reason: "杭州最原汁原味的社区，拍人文照片的天堂。",
    bestTime: "上午 8:00-11:00", estimatedTime: "1.5-2小时", cost: "免费",
    nearbySpots: ["凤凰山", "南宋御街", "鼓楼"],
    tags: ["City Walk", "摄影", "古建筑"],
    imageUrl: "https://picsum.photos/800/600?random=43",
    imageColor: "#9E8B7A",
  },
  {
    id: "hg-hz-4", name: "单向空间·乐堤港店", city: "杭州", region: "华东",
    lat: 30.31, lng: 120.15,
    description: "三层楼的独立书店，设计极简，窗边座位可以俯瞰运河，常有作家见面会。",
    reason: "杭州文艺青年的精神角落，远超普通书店体验。",
    bestTime: "下午 2:00-6:00", estimatedTime: "2-3小时", cost: "免费（咖啡 ¥35-55）",
    nearbySpots: ["运河天地", "拱宸桥", "小河直街"],
    tags: ["书店", "咖啡馆", "艺术空间"],
    imageUrl: "https://picsum.photos/800/600?random=44",
    imageColor: "#6B7B8D",
  },

  // ==================== 华东 · 苏州 ====================
  {
    id: "hg-sz-1", name: "平江路深处·丁香巷", city: "苏州", region: "华东",
    lat: 31.315, lng: 120.63,
    description: "平江路主街之外的小巷迷宫，丁香巷、大儒巷藏着本地人喝茶听评弹的老宅。",
    reason: "99%的游客只走主街，深巷里才是真苏州。",
    bestTime: "下午 3:00-6:00", estimatedTime: "2-3小时", cost: "免费（评弹 ¥50-80）",
    nearbySpots: ["平江路", "拙政园", "狮子林"],
    tags: ["City Walk", "古建筑", "非遗体验"],
    imageUrl: "https://picsum.photos/800/600?random=45",
    imageColor: "#7B8FA1",
  },
  {
    id: "hg-sz-2", name: "葑门横街菜市场", city: "苏州", region: "华东",
    lat: 31.298, lng: 120.645,
    description: "苏州最有烟火气的老菜场，清晨的糕团、糖粥、生煎包，本地人排队也要买。",
    reason: "比任何美食街都正宗，苏州人的早晨从这里开始。",
    bestTime: "早上 6:30-9:00", estimatedTime: "1.5-2小时", cost: "¥30-50/人",
    nearbySpots: ["葑门", "苏州大学", "十全街"],
    tags: ["美食", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=46",
    imageColor: "#D4A574",
  },
  {
    id: "hg-sz-3", name: "苏州丝绸博物馆", city: "苏州", region: "华东",
    lat: 31.328, lng: 120.615,
    description: "小而精的博物馆，能看到从蚕茧到织锦的全过程，还有非遗传承人现场演示。",
    reason: "免费且人少，比苏州博物馆更深入丝绸文化本身。",
    bestTime: "上午 9:00-11:30", estimatedTime: "1.5-2小时", cost: "免费",
    nearbySpots: ["北寺塔", "苏州博物馆", "拙政园"],
    tags: ["博物馆", "非遗体验", "小众"],
    imageUrl: "https://picsum.photos/800/600?random=47",
    imageColor: "#E8D5B7",
  },

  // ==================== 华东 · 南京 ====================
  {
    id: "hg-nj-1", name: "颐和路民国公馆区", city: "南京", region: "华东",
    lat: 32.055, lng: 118.768,
    description: "半部民国史藏在颐和路的梧桐树影里，两百多栋民国公馆静立，秋天满地金黄。",
    reason: "没有门票没有游客，却是南京最美的街区之一。",
    bestTime: "下午 3:00-5:30（秋天最佳）", estimatedTime: "2-3小时", cost: "免费",
    nearbySpots: ["先锋书店", "南京大学", "鼓楼"],
    tags: ["City Walk", "摄影", "古建筑"],
    imageUrl: "https://picsum.photos/800/600?random=48",
    imageColor: "#D4A017",
  },
  {
    id: "hg-nj-2", name: "先锋书店·五台山总店", city: "南京", region: "华东",
    lat: 32.052, lng: 118.77,
    description: "由地下车库改造的独立书店，十字架灯光、巨大的思想者雕塑，文艺朝圣地。",
    reason: "中国最美书店之一，地下空间的仪式感无可替代。",
    bestTime: "下午 2:00-6:00", estimatedTime: "1.5-2小时", cost: "免费（咖啡 ¥30-45）",
    nearbySpots: ["南京大学", "五台山体育馆", "颐和路"],
    tags: ["书店", "咖啡馆", "艺术空间"],
    imageUrl: "https://picsum.photos/800/600?random=49",
    imageColor: "#5C4033",
  },
  {
    id: "hg-nj-3", name: "老门东·三条营", city: "南京", region: "华东",
    lat: 32.015, lng: 118.788,
    description: "老门东主街深处的小巷，藏着金陵刻经处和非遗传习所，能看到匠人手工刻版。",
    reason: "避开主街人流，发现非遗活态传承的惊喜。",
    bestTime: "上午 10:00-12:00", estimatedTime: "2-3小时", cost: "免费（刻经体验 ¥80）",
    nearbySpots: ["老门东", "中华门", "大报恩寺"],
    tags: ["非遗体验", "古建筑", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=50",
    imageColor: "#7B6B5E",
  },
  {
    id: "hg-nj-4", name: "科巷菜场美食街", city: "南京", region: "华东",
    lat: 32.04, lng: 118.79,
    description: "南京本地人的美食后厨，鸭血粉丝汤、牛肉锅贴、桂花糖芋苗，从街头吃到巷尾。",
    reason: "比夫子庙便宜一半，味道正宗三倍。",
    bestTime: "中午 11:00-13:00", estimatedTime: "1-1.5小时", cost: "¥40-60/人",
    nearbySpots: ["总统府", "1912街区", "新街口"],
    tags: ["美食", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=51",
    imageColor: "#C41E3A",
  },

  // ==================== 华东 · 上海 ====================
  {
    id: "hg-sh-1", name: "南昌路·人文散步", city: "上海", region: "华东",
    lat: 31.215, lng: 121.458,
    description: "法租界最安静的马路之一，沿路是独立咖啡馆、小众画廊和百年老洋房。",
    reason: "武康路已被游客占领，南昌路才是本地人的秘密据点。",
    bestTime: "下午 2:00-5:00", estimatedTime: "2-3小时", cost: "免费（咖啡 ¥35-60）",
    nearbySpots: ["淮海中路", "思南路", "复兴公园"],
    tags: ["City Walk", "咖啡馆", "摄影"],
    imageUrl: "https://picsum.photos/800/600?random=52",
    imageColor: "#6B8E6B",
  },
  {
    id: "hg-sh-2", name: "1933老场坊", city: "上海", region: "华东",
    lat: 31.258, lng: 121.495,
    description: "前身为远东第一屠宰场，混凝土迷宫般的建筑，现在是设计师集合店和展览空间。",
    reason: "建筑本身就是艺术品，每层都有意想不到的惊喜。",
    bestTime: "上午 10:00-12:00", estimatedTime: "1.5-2小时", cost: "免费（展览另付）",
    nearbySpots: ["1933老场坊", "多伦路文化街", "鲁迅公园"],
    tags: ["艺术空间", "摄影", "小众"],
    imageUrl: "https://picsum.photos/800/600?random=53",
    imageColor: "#8B8B83",
  },
  {
    id: "hg-sh-3", name: "M50创意园", city: "上海", region: "华东",
    lat: 31.248, lng: 121.43,
    description: "苏州河畔的老厂房改造艺术区，画廊、艺术家工作室、独立设计店铺聚集。",
    reason: "上海最有活力的当代艺术社区，每个角落都是展览。",
    bestTime: "下午 1:00-5:00", estimatedTime: "2-3小时", cost: "免费",
    nearbySpots: ["苏州河", "M50", "静安寺"],
    tags: ["艺术空间", "摄影", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=54",
    imageColor: "#A0A0A0",
  },
  {
    id: "hg-sh-4", name: "衡山·和集", city: "上海", region: "华东",
    lat: 31.21, lng: 121.445,
    description: "三层独立书店，一层电影书籍+咖啡馆，二层设计杂志，三层文化沙龙空间。",
    reason: "上海最精致的独立书店，选书品位一绝。",
    bestTime: "下午 2:00-6:00", estimatedTime: "1.5-2小时", cost: "免费（咖啡 ¥35-50）",
    nearbySpots: ["衡山路", "上海图书馆", "武康大楼"],
    tags: ["书店", "咖啡馆", "艺术空间"],
    imageUrl: "https://picsum.photos/800/600?random=55",
    imageColor: "#4A4A3A",
  },

  // ==================== 华东 · 厦门 ====================
  {
    id: "hg-xm-1", name: "沙坡尾艺术西区", city: "厦门", region: "华东",
    lat: 24.44, lng: 118.08,
    description: "老渔港改造的文创街区，涂鸦墙、独立咖啡馆、手工市集和渔港落日。",
    reason: "比鼓浪屿安静，年轻人的创意聚集地。",
    bestTime: "下午 3:00-7:00", estimatedTime: "2-3小时", cost: "免费（咖啡 ¥30-50）",
    nearbySpots: ["厦门大学", "南普陀寺", "猫街"],
    tags: ["艺术空间", "咖啡馆", "夜景"],
    imageUrl: "https://picsum.photos/800/600?random=56",
    imageColor: "#4F8EF7",
  },
  {
    id: "hg-xm-2", name: "第八菜市场", city: "厦门", region: "华东",
    lat: 24.452, lng: 118.08,
    description: "厦门最地道的海鲜干货市场，沙茶面、海蛎煎、土笋冻，老厦门的味道。",
    reason: "每个摊位前都是本地阿婆在挑选，美食纪录片取景地。",
    bestTime: "早上 7:00-10:00", estimatedTime: "1-1.5小时", cost: "¥40-80/人",
    nearbySpots: ["中山路", "轮渡码头", "鼓浪屿"],
    tags: ["美食", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=57",
    imageColor: "#E87040",
  },
  {
    id: "hg-xm-3", name: "不在书店", city: "厦门", region: "华东",
    lat: 24.448, lng: 118.078,
    description: "华新路老别墅里的独立书店，院里有棵大榕树，安静到能听见翻书声。",
    reason: "厦门最有故事的独立书店，曾是全国最美书店之一。",
    bestTime: "下午 1:00-5:00", estimatedTime: "1.5-2小时", cost: "免费（咖啡 ¥30-45）",
    nearbySpots: ["华新路", "中山公园", "溪岸路花鸟市场"],
    tags: ["书店", "咖啡馆", "古建筑"],
    imageUrl: "https://picsum.photos/800/600?random=58",
    imageColor: "#8FBC8F",
  },

  // ==================== 华东 · 泉州 ====================
  {
    id: "hg-qz-1", name: "西街·开元寺后巷", city: "泉州", region: "华东",
    lat: 24.917, lng: 118.585,
    description: "避开西街主街的人潮，钻进开元寺旁的窄巷，红砖古厝、燕尾脊随处可见。",
    reason: "泉州世界遗产的核心区，深巷里藏着闽南建筑精华。",
    bestTime: "上午 8:00-11:00", estimatedTime: "2-3小时", cost: "免费",
    nearbySpots: ["开元寺", "西街", "泉州钟楼"],
    tags: ["古建筑", "City Walk", "摄影"],
    imageUrl: "https://picsum.photos/800/600?random=59",
    imageColor: "#C04000",
  },
  {
    id: "hg-qz-2", name: "蟳埔村", city: "泉州", region: "华东",
    lat: 24.88, lng: 118.62,
    description: "以簪花围闻名的渔村，女性头戴鲜花是活着的非遗，牡蛎壳墙是独特的建筑景观。",
    reason: "簪花围是非遗活化石，拍照超出片且文化含金量高。",
    bestTime: "上午 9:00-12:00", estimatedTime: "2-3小时", cost: "免费（簪花体验 ¥50）",
    nearbySpots: ["清净寺", "关帝庙", "天后宫"],
    tags: ["非遗体验", "摄影", "自然风光"],
    imageUrl: "https://picsum.photos/800/600?random=60",
    imageColor: "#FF6B8A",
  },
  {
    id: "hg-qz-3", name: "涂门街·清净寺", city: "泉州", region: "华东",
    lat: 24.905, lng: 118.588,
    description: "中国现存最古老的伊斯兰教寺院，与关帝庙仅一墙之隔，见证泉州多元文化交融。",
    reason: "全世界独一无二的宗教共存奇观，千年石柱令人震撼。",
    bestTime: "下午 3:00-5:00", estimatedTime: "1-1.5小时", cost: "¥3",
    nearbySpots: ["关帝庙", "天后宫", "文庙"],
    tags: ["古建筑", "历史文化", "小众"],
    imageUrl: "https://picsum.photos/800/600?random=61",
    imageColor: "#D4C5A9",
  },

  // ==================== 华东 · 青岛 ====================
  {
    id: "hg-qd-1", name: "八大关·临淮关路", city: "青岛", region: "华东",
    lat: 36.053, lng: 120.355,
    description: "八大关最美的一条梧桐隧道，春夏绿荫如盖，秋天满地金黄，几乎没有游客。",
    reason: "比居庸关路安静一百倍，是八大关真正的秘境。",
    bestTime: "下午 3:00-5:30", estimatedTime: "1-2小时", cost: "免费",
    nearbySpots: ["八大关", "第二海水浴场", "花石楼"],
    tags: ["City Walk", "摄影", "自然风光"],
    imageUrl: "https://picsum.photos/800/600?random=62",
    imageColor: "#228B22",
  },
  {
    id: "hg-qd-2", name: "大学路·鱼山路转角", city: "青岛", region: "华东",
    lat: 36.065, lng: 120.338,
    description: "网红转角只是入口，大学路两侧的老洋房、咖啡馆和独立书店才是真正的宝藏。",
    reason: "转角打卡后别走，整条街的文艺氛围可以泡一下午。",
    bestTime: "下午 1:00-5:00", estimatedTime: "2-3小时", cost: "免费（咖啡 ¥30-50）",
    nearbySpots: ["青岛美术馆", "老舍故居", "信号山"],
    tags: ["咖啡馆", "书店", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=63",
    imageColor: "#4169E1",
  },
  {
    id: "hg-qd-3", name: "黄岛路菜市场", city: "青岛", region: "华东",
    lat: 36.067, lng: 120.318,
    description: "老青岛的烟火气集中地，海鲜啤酒烧烤一条龙，本地大爷拎着塑料袋打啤酒。",
    reason: "体验青岛市民生活的活标本，塑料袋装啤酒是独有奇观。",
    bestTime: "下午 4:00-7:00", estimatedTime: "1-1.5小时", cost: "¥50-80/人",
    nearbySpots: ["栈桥", "天主教堂", "中山路"],
    tags: ["美食", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=64",
    imageColor: "#FFD700",
  },

  // ==================== 华南 · 广州 ====================
  {
    id: "hg-gz-1", name: "东山口·培正路", city: "广州", region: "华南",
    lat: 23.125, lng: 113.295,
    description: "广州的「鼓浪屿」，红砖洋楼、独立咖啡馆、买手店和设计工作室的聚集地。",
    reason: "文青浓度最高的街区，每一扇门后面都可能是一间画廊。",
    bestTime: "下午 2:00-6:00", estimatedTime: "2-3小时", cost: "免费（咖啡 ¥30-55）",
    nearbySpots: ["东山湖公园", "逵园", "新河浦"],
    tags: ["City Walk", "咖啡馆", "摄影", "艺术空间"],
    imageUrl: "https://picsum.photos/800/600?random=65",
    imageColor: "#8B3A3A",
  },
  {
    id: "hg-gz-2", name: "西关·恩宁路", city: "广州", region: "华南",
    lat: 23.118, lng: 113.235,
    description: "广州最美老街，骑楼连绵，铜器铺叮当作响，永庆坊的非遗体验藏在巷子深处。",
    reason: "比上下九安静且更有味道，真正的老西关风情。",
    bestTime: "上午 9:00-12:00", estimatedTime: "2-3小时", cost: "免费（非遗体验 ¥50-100）",
    nearbySpots: ["永庆坊", "上下九", "荔枝湾"],
    tags: ["古建筑", "非遗体验", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=66",
    imageColor: "#A0522D",
  },
  {
    id: "hg-gz-3", name: "1200bookshop·体育东店", city: "广州", region: "华南",
    lat: 23.133, lng: 113.328,
    description: "24小时不打烊的独立书店，沙发客文化，深夜常有读书分享会和不眠的读者。",
    reason: "广州最具人文温度的深夜书店，为城市留一盏灯。",
    bestTime: "晚上 8:00-深夜", estimatedTime: "1.5-2小时", cost: "免费（咖啡 ¥30-50）",
    nearbySpots: ["体育西", "珠江新城", "正佳广场"],
    tags: ["书店", "咖啡馆", "艺术空间"],
    imageUrl: "https://picsum.photos/800/600?random=67",
    imageColor: "#2F2F2F",
  },
  {
    id: "hg-gz-4", name: "泮塘五约", city: "广州", region: "华南",
    lat: 23.125, lng: 113.23,
    description: "荔枝湾深处的千年古村，青石板路、祠堂、手工作坊，时间在这里慢了百年。",
    reason: "荔湾湖公园旁最被低估的文艺聚落。",
    bestTime: "下午 3:00-6:00", estimatedTime: "1.5-2小时", cost: "免费",
    nearbySpots: ["荔枝湾", "荔湾湖公园", "永庆坊"],
    tags: ["古建筑", "City Walk", "摄影"],
    imageUrl: "https://picsum.photos/800/600?random=68",
    imageColor: "#5F9EA0",
  },

  // ==================== 华南 · 深圳 ====================
  {
    id: "hg-sz-1", name: "华侨城创意园·北区", city: "深圳", region: "华南",
    lat: 22.543, lng: 113.97,
    description: "旧厂房改造的文艺社区，周末有T街创意市集，独立设计师和街头艺人的聚集地。",
    reason: "深圳最文艺的角落，每个周末都有新惊喜。",
    bestTime: "周末下午 2:00-6:00", estimatedTime: "2-3小时", cost: "免费（市集购物另算）",
    nearbySpots: ["华侨城", "世界之窗", "欢乐海岸"],
    tags: ["艺术空间", "咖啡馆", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=69",
    imageColor: "#708090",
  },
  {
    id: "hg-sz-2", name: "蛇口·海上世界文化艺术中心", city: "深圳", region: "华南",
    lat: 22.485, lng: 113.915,
    description: "槇文彦设计的海边美术馆，面朝大海，看展喝茶，是深圳难得的慢节奏角落。",
    reason: "建筑与海景完美融合，深圳最具设计感的文化空间。",
    bestTime: "下午 2:00-5:30", estimatedTime: "2-3小时", cost: "免费（特展另付）",
    nearbySpots: ["海上世界", "蛇口老街", "深圳湾公园"],
    tags: ["艺术空间", "博物馆", "摄影"],
    imageUrl: "https://picsum.photos/800/600?random=70",
    imageColor: "#87CEEB",
  },
  {
    id: "hg-sz-3", name: "较场尾·海边的民宿村", city: "深圳", region: "华南",
    lat: 22.58, lng: 114.485,
    description: "深圳唯一有海岸线的村子，彩色民宿、冲浪俱乐部和海边的篝火晚会。",
    reason: "不用飞东南亚，深圳就有文艺海滩度假感。",
    bestTime: "下午 4:00-日落", estimatedTime: "半天", cost: "免费（民宿 ¥300-800/晚）",
    nearbySpots: ["大鹏所城", "金沙湾", "杨梅坑"],
    tags: ["海边", "自然风光", "摄影"],
    imageUrl: "https://picsum.photos/800/600?random=71",
    imageColor: "#00CED1",
  },

  // ==================== 华南 · 潮州 ====================
  {
    id: "hg-cz-1", name: "牌坊街·甲第巷", city: "潮州", region: "华南",
    lat: 23.665, lng: 116.645,
    description: "牌坊街主街旁的古巷，明清大夫第、资政第保存完好，每家每户都有故事。",
    reason: "比牌坊街安静百倍，潮州古民居的精华都在这里。",
    bestTime: "上午 8:00-11:00", estimatedTime: "1.5-2小时", cost: "免费",
    nearbySpots: ["牌坊街", "开元寺", "广济桥"],
    tags: ["古建筑", "City Walk", "摄影"],
    imageUrl: "https://picsum.photos/800/600?random=72",
    imageColor: "#B8860B",
  },
  {
    id: "hg-cz-2", name: "西湖边·潮州工夫茶", city: "潮州", region: "华南",
    lat: 23.67, lng: 116.638,
    description: "潮州西湖边的老茶馆，本地阿伯从早坐到晚，三杯功夫茶配半天的闲话。",
    reason: "体验最正宗的潮州工夫茶文化，一泡凤凰单丛喝一下午。",
    bestTime: "下午 2:00-5:00", estimatedTime: "1.5-2小时", cost: "¥20-50/人",
    nearbySpots: ["潮州西湖", "许驸马府", "己略黄公祠"],
    tags: ["非遗体验", "美食", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=73",
    imageColor: "#556B2F",
  },
  {
    id: "hg-cz-3", name: "龙湖古寨", city: "潮州", region: "华南",
    lat: 23.62, lng: 116.68,
    description: "千年古寨，一百多座祠堂府第沿直街排列，潮汕建筑艺术的博物馆。",
    reason: "比潮州古城更原始，没有商业化，是建筑爱好者的天堂。",
    bestTime: "上午 9:00-12:00", estimatedTime: "2-3小时", cost: "免费",
    nearbySpots: ["韩江", "潮州古城"],
    tags: ["古建筑", "摄影", "历史文化"],
    imageUrl: "https://picsum.photos/800/600?random=74",
    imageColor: "#8B7355",
  },

  // ==================== 华南 · 汕头 ====================
  {
    id: "hg-st-1", name: "小公园·安平路", city: "汕头", region: "华南",
    lat: 23.36, lng: 116.67,
    description: "汕头老城的心脏，骑楼群保存完好，傍晚时分金光照在斑驳的墙面上绝美。",
    reason: "汕头最上镜的街景，电影感十足。",
    bestTime: "下午 3:00-5:30", estimatedTime: "1.5-2小时", cost: "免费",
    nearbySpots: ["小公园亭", "汕头开埠文化陈列馆", "西堤公园"],
    tags: ["City Walk", "摄影", "古建筑"],
    imageUrl: "https://picsum.photos/800/600?random=75",
    imageColor: "#DAA520",
  },
  {
    id: "hg-st-2", name: "福合埕牛肉丸老店", city: "汕头", region: "华南",
    lat: 23.365, lng: 116.678,
    description: "四十年老店，手打牛肉丸弹到能打乒乓球，凌晨还在营业的深夜食堂。",
    reason: "汕头牛肉丸的天花板，本地人从小吃到大的味道。",
    bestTime: "晚上 7:00-10:00", estimatedTime: "1小时", cost: "¥60-100/人",
    nearbySpots: ["小公园", "中山公园"],
    tags: ["美食"],
    imageUrl: "https://picsum.photos/800/600?random=76",
    imageColor: "#CD5C5C",
  },

  // ==================== 西南 · 成都 ====================
  {
    id: "hg-cd-1", name: "玉林路·芳草街", city: "成都", region: "西南",
    lat: 30.625, lng: 104.048,
    description: "赵雷唱的小酒馆只是入口，整条玉林路藏着独立书店、精酿酒吧和老牌串串店。",
    reason: "成都最有生活气息的街区，越夜越精彩。",
    bestTime: "晚上 7:00-深夜", estimatedTime: "2-3小时", cost: "¥80-150/人",
    nearbySpots: ["小酒馆", "玉林菜市场", "四川省体育馆"],
    tags: ["美食", "咖啡馆", "夜景", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=77",
    imageColor: "#FF6347",
  },
  {
    id: "hg-cd-2", name: "东郊记忆", city: "成都", region: "西南",
    lat: 30.66, lng: 104.12,
    description: "前苏联援建的电子管厂改造的文创园区，蒸汽朋克风配涂鸦墙和LiveHouse。",
    reason: "成都最酷的工业风打卡地，经常有免费展览。",
    bestTime: "下午 2:00-6:00", estimatedTime: "2-3小时", cost: "免费",
    nearbySpots: ["建设路美食街", "成都东站", "成都理工"],
    tags: ["艺术空间", "摄影", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=78",
    imageColor: "#696969",
  },
  {
    id: "hg-cd-3", name: "文殊院·香园", city: "成都", region: "西南",
    lat: 30.675, lng: 104.068,
    description: "文殊院旁边的素食茶馆，竹椅、盖碗茶、素食点心，成都慢生活的极致。",
    reason: "比人民公园更安静，素食和茶道体验一流水准。",
    bestTime: "下午 2:00-5:00", estimatedTime: "1.5-2小时", cost: "¥50-80/人",
    nearbySpots: ["文殊院", "文殊坊", "天府广场"],
    tags: ["美食", "非遗体验", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=79",
    imageColor: "#6B8E23",
  },
  {
    id: "hg-cd-4", name: "無早书店", city: "成都", region: "西南",
    lat: 30.65, lng: 104.078,
    description: "成都最早的独立杂志书店，隔壁是無早小食，抹茶千层配独立出版物。",
    reason: "成都独立书店的标杆，选书和选品都有好品位。",
    bestTime: "下午 1:00-5:00", estimatedTime: "1.5-2小时", cost: "免费（咖啡甜品 ¥40-60）",
    nearbySpots: ["太古里", "IFS", "镗钯街"],
    tags: ["书店", "咖啡馆"],
    imageUrl: "https://picsum.photos/800/600?random=80",
    imageColor: "#DEB887",
  },

  // ==================== 西南 · 重庆 ====================
  {
    id: "hg-cq-1", name: "山城巷", city: "重庆", region: "西南",
    lat: 29.553, lng: 106.572,
    description: "悬崖上的老街，沿崖壁而建的吊脚楼和石梯，灯笼亮起时的夜景绝了。",
    reason: "比洪崖洞安静一百倍，悬崖步道的视角独一无二。",
    bestTime: "傍晚 5:00-8:00", estimatedTime: "1.5-2小时", cost: "免费",
    nearbySpots: ["解放碑", "十八梯", "洪崖洞"],
    tags: ["City Walk", "夜景", "摄影"],
    imageUrl: "https://picsum.photos/800/600?random=81",
    imageColor: "#B22222",
  },
  {
    id: "hg-cq-2", name: "交通茶馆", city: "重庆", region: "西南",
    lat: 29.51, lng: 106.547,
    description: "重庆最老茶馆，三十多年没变过样，竹椅木桌搪瓷杯，一碗茶坐一下午。",
    reason: "时间的活化石，重庆最有江湖气的地方。",
    bestTime: "下午 2:00-5:00", estimatedTime: "1.5-2小时", cost: "¥10-20/人",
    nearbySpots: ["四川美院", "涂鸦一条街", "铁路中学"],
    tags: ["非遗体验", "摄影", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=82",
    imageColor: "#8B4513",
  },
  {
    id: "hg-cq-3", name: "下浩里老街", city: "重庆", region: "西南",
    lat: 29.545, lng: 106.59,
    description: "南岸老街改造的文创街区，保留了原住民的生活痕迹，长江索道从头顶划过。",
    reason: "比龙门浩老街更原生态，能看到重庆最真实的一面。",
    bestTime: "下午 3:00-6:00", estimatedTime: "2-3小时", cost: "免费",
    nearbySpots: ["龙门浩老街", "长江索道", "南山"],
    tags: ["City Walk", "摄影", "古建筑"],
    imageUrl: "https://picsum.photos/800/600?random=83",
    imageColor: "#A0522D",
  },
  {
    id: "hg-cq-4", name: "鹅岭贰厂", city: "重庆", region: "西南",
    lat: 29.55, lng: 106.54,
    description: "民国中央银行印钞厂改造的文创公园，天台可俯瞰两江交汇，电影取景地。",
    reason: "视野无敌的天台咖啡馆，拍重庆天际线的最佳机位。",
    bestTime: "下午 4:00-7:00（看日落）", estimatedTime: "2-3小时", cost: "免费（咖啡 ¥35-50）",
    nearbySpots: ["鹅岭公园", "李子坝轻轨站", "佛图关"],
    tags: ["艺术空间", "摄影", "夜景", "咖啡馆"],
    imageUrl: "https://picsum.photos/800/600?random=84",
    imageColor: "#696969",
  },

  // ==================== 西南 · 大理 ====================
  {
    id: "hg-dl-1", name: "龙龛码头", city: "大理", region: "西南",
    lat: 25.63, lng: 100.18,
    description: "比才村码头小众十倍的看日出地点，水杉林立在洱海边，晨雾中如梦如幻。",
    reason: "大理最美的日出机位，人少到可以承包整片海岸。",
    bestTime: "日出前 6:30-9:00", estimatedTime: "1.5-2小时", cost: "免费",
    nearbySpots: ["大理古城", "才村码头", "崇圣寺三塔"],
    tags: ["自然风光", "摄影", "海边"],
    imageUrl: "https://picsum.photos/800/600?random=85",
    imageColor: "#FF7F50",
  },
  {
    id: "hg-dl-2", name: "喜洲·转角楼", city: "大理", region: "西南",
    lat: 25.855, lng: 100.118,
    description: "喜洲古镇最经典的转角建筑，旁边的稻田咖啡可以对着苍山发呆一下午。",
    reason: "游客去喜洲打卡就走了，但坐下来喝杯咖啡才是正确的打开方式。",
    bestTime: "下午 2:00-5:00", estimatedTime: "2-3小时", cost: "免费（咖啡 ¥30-50）",
    nearbySpots: ["喜洲古镇", "海舌公园", "周城扎染"],
    tags: ["咖啡馆", "摄影", "古建筑"],
    imageUrl: "https://picsum.photos/800/600?random=86",
    imageColor: "#DAA520",
  },
  {
    id: "hg-dl-3", name: "周城·扎染体验", city: "大理", region: "西南",
    lat: 25.89, lng: 100.105,
    description: "白族扎染的发源地，家家户户门前晾着蓝白布，可以亲手做一块扎染方巾。",
    reason: "真正的非遗活态传承，自己动手染一块比买纪念品有意义得多。",
    bestTime: "上午 9:00-12:00", estimatedTime: "2-3小时", cost: "¥80-150/人（体验费）",
    nearbySpots: ["喜洲古镇", "蝴蝶泉", "洱海"],
    tags: ["非遗体验", "摄影", "艺术空间"],
    imageUrl: "https://picsum.photos/800/600?random=87",
    imageColor: "#4169E1",
  },
  {
    id: "hg-dl-4", name: "床单厂艺术区", city: "大理", region: "西南",
    lat: 25.678, lng: 100.158,
    description: "大理古城里的废弃床单厂改造，周末有手作市集，独立音乐人和流浪诗人汇聚。",
    reason: "大理文青的真正聚集地，每个摊位后面都有一个故事。",
    bestTime: "周末下午 2:00-6:00", estimatedTime: "1.5-2小时", cost: "免费",
    nearbySpots: ["大理古城", "人民路", "洋人街"],
    tags: ["艺术空间", "City Walk", "书店"],
    imageUrl: "https://picsum.photos/800/600?random=88",
    imageColor: "#9370DB",
  },

  // ==================== 西南 · 丽江 ====================
  {
    id: "hg-lj-1", name: "白沙古镇·壁画", city: "丽江", region: "西南",
    lat: 26.958, lng: 100.215,
    description: "比大研古城安静得多的纳西古镇，白沙壁画是明代宗教艺术的瑰宝。",
    reason: "游客都挤在大研，白沙才是丽江原本的样子。",
    bestTime: "上午 9:00-12:00", estimatedTime: "2-3小时", cost: "壁画 ¥30",
    nearbySpots: ["玉龙雪山", "束河古镇", "大研古城"],
    tags: ["古建筑", "历史文化", "摄影"],
    imageUrl: "https://picsum.photos/800/600?random=89",
    imageColor: "#B8860B",
  },
  {
    id: "hg-lj-2", name: "文海", city: "丽江", region: "西南",
    lat: 26.99, lng: 100.17,
    description: "玉龙雪山脚下的高山湖泊，夏季开满野花，牛羊在湖边吃草，几乎没有游客。",
    reason: "比拉市海美十倍，而且完全免费。",
    bestTime: "6-8月（花季全天）", estimatedTime: "半天", cost: "免费",
    nearbySpots: ["玉龙雪山", "白沙古镇"],
    tags: ["自然风光", "摄影", "户外"],
    imageUrl: "https://picsum.photos/800/600?random=90",
    imageColor: "#228B22",
  },
  {
    id: "hg-lj-3", name: "忠义市场", city: "丽江", region: "西南",
    lat: 26.868, lng: 100.232,
    description: "丽江最大的本地菜市场，纳西阿妈摆摊卖野生菌、腊排骨和鸡豆凉粉。",
    reason: "古城里最接近丽江本地生活的地方，比四方街真实一百倍。",
    bestTime: "早上 7:00-10:00", estimatedTime: "1-1.5小时", cost: "¥30-50/人",
    nearbySpots: ["大研古城", "木府", "四方街"],
    tags: ["美食", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=91",
    imageColor: "#CD853F",
  },

  // ==================== 西南 · 昆明 ====================
  {
    id: "hg-km-1", name: "篆新农贸市场", city: "昆明", region: "西南",
    lat: 25.043, lng: 102.702,
    description: "昆明最大最全的菜市场，菌子季时几十种野生菌摆满摊位，云南的味觉博物馆。",
    reason: "一个菜市场读懂云南，美食纪录片多次取景。",
    bestTime: "早上 8:00-11:00", estimatedTime: "1.5-2小时", cost: "¥50-100/人",
    nearbySpots: ["翠湖公园", "云南大学", "陆军讲武堂"],
    tags: ["美食", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=92",
    imageColor: "#FF6347",
  },
  {
    id: "hg-km-2", name: "云南铁路博物馆", city: "昆明", region: "西南",
    lat: 25.04, lng: 102.72,
    description: "百年滇越铁路的历史见证，实物火车头停在博物馆内，窄轨蒸汽机车触手可及。",
    reason: "小众但极其震撼，米轨小火车的传奇故事。",
    bestTime: "上午 9:00-12:00", estimatedTime: "1.5-2小时", cost: "¥10",
    nearbySpots: ["昆明北站", "翠湖公园"],
    tags: ["博物馆", "历史文化", "小众"],
    imageUrl: "https://picsum.photos/800/600?random=93",
    imageColor: "#8B4513",
  },
  {
    id: "hg-km-3", name: "斗南花市", city: "昆明", region: "西南",
    lat: 24.91, lng: 102.78,
    description: "亚洲最大的鲜花交易市场，晚上8点开市，几块钱买一大把玫瑰的快乐。",
    reason: "花比菜便宜，昆明的浪漫浓度最高的地方。",
    bestTime: "晚上 8:00-10:00（夜市）", estimatedTime: "1.5-2小时", cost: "¥20-50/人",
    nearbySpots: ["斗南地铁站", "滇池"],
    tags: ["City Walk", "摄影", "小众"],
    imageUrl: "https://picsum.photos/800/600?random=94",
    imageColor: "#FF69B4",
  },

  // ==================== 华北 · 北京 ====================
  {
    id: "hg-bj-1", name: "杨梅竹斜街", city: "北京", region: "华北",
    lat: 39.893, lng: 116.395,
    description: "前门旁边被遗忘的胡同，藏着模范书局、铃木食堂和民国老建筑。",
    reason: "比南锣鼓巷安静一百倍，胡同里的设计书店全国闻名。",
    bestTime: "下午 2:00-5:00", estimatedTime: "2-3小时", cost: "免费（咖啡 ¥35-60）",
    nearbySpots: ["前门", "大栅栏", "琉璃厂"],
    tags: ["City Walk", "书店", "咖啡馆", "古建筑"],
    imageUrl: "https://picsum.photos/800/600?random=95",
    imageColor: "#8B8378",
  },
  {
    id: "hg-bj-2", name: "五道营胡同", city: "北京", region: "华北",
    lat: 39.945, lng: 116.41,
    description: "雍和宫旁最文艺的胡同，独立咖啡馆、手工皮具店和猫咪主题小店。",
    reason: "比南锣更有设计感，每家店都有自己的态度。",
    bestTime: "下午 1:00-5:00", estimatedTime: "1.5-2小时", cost: "免费（咖啡 ¥35-55）",
    nearbySpots: ["雍和宫", "国子监", "地坛公园"],
    tags: ["City Walk", "咖啡馆", "书店"],
    imageUrl: "https://picsum.photos/800/600?random=96",
    imageColor: "#CD853F",
  },
  {
    id: "hg-bj-3", name: "红砖美术馆", city: "北京", region: "华北",
    lat: 40.02, lng: 116.52,
    description: "红砖建筑本身就是艺术品，园林设计融合苏州园林与当代极简，出片率100%。",
    reason: "北京最被低估的美术馆，建筑和展品同样精彩。",
    bestTime: "上午 10:00-13:00", estimatedTime: "2-3小时", cost: "¥120",
    nearbySpots: ["798艺术区", "望京", "马泉营"],
    tags: ["艺术空间", "摄影", "博物馆"],
    imageUrl: "https://picsum.photos/800/600?random=97",
    imageColor: "#B22222",
  },
  {
    id: "hg-bj-4", name: "模范书局·诗空间", city: "北京", region: "华北",
    lat: 39.898, lng: 116.36,
    description: "百年教堂改造的书店，穹顶下的阅读空间，古籍和雕版印刷是特色。",
    reason: "教堂+书店的神仙组合，北京最美的阅读空间之一。",
    bestTime: "下午 2:00-5:00", estimatedTime: "1.5-2小时", cost: "免费（咖啡 ¥35-50）",
    nearbySpots: ["佟麟阁路", "西单", "金融街"],
    tags: ["书店", "咖啡馆", "古建筑"],
    imageUrl: "https://picsum.photos/800/600?random=98",
    imageColor: "#A0522D",
  },

  // ==================== 华北 · 天津 ====================
  {
    id: "hg-tj-1", name: "五大道·民园西里", city: "天津", region: "华北",
    lat: 39.11, lng: 117.195,
    description: "五大道深处的胡同，老洋房改成的小众艺术空间和咖啡馆，周末有创意市集。",
    reason: "五大道的精华不在主路而在这些小胡同里。",
    bestTime: "周末下午 2:00-5:00", estimatedTime: "2-3小时", cost: "免费（咖啡 ¥30-50）",
    nearbySpots: ["民园广场", "五大道", "小白楼"],
    tags: ["City Walk", "咖啡馆", "艺术空间"],
    imageUrl: "https://picsum.photos/800/600?random=99",
    imageColor: "#D2691E",
  },
  {
    id: "hg-tj-2", name: "天津古文化街·杨柳青年画社", city: "天津", region: "华北",
    lat: 39.143, lng: 117.188,
    description: "非遗传承人现场演示杨柳青年画制作，从刻版到套印，可以自己上手体验。",
    reason: "游客买年画就走了，但亲手印一张才是真正的非遗体验。",
    bestTime: "上午 10:00-12:00", estimatedTime: "1-1.5小时", cost: "体验 ¥50-100",
    nearbySpots: ["古文化街", "天津之眼", "海河"],
    tags: ["非遗体验", "古建筑"],
    imageUrl: "https://picsum.photos/800/600?random=100",
    imageColor: "#DC143C",
  },
  {
    id: "hg-tj-3", name: "意大利风情区·自由道", city: "天津", region: "华北",
    lat: 39.138, lng: 117.198,
    description: "原意大利租界，马可波罗广场周边的小路比主街安静，每个转角都有老建筑。",
    reason: "比主街安静且有味道，夕阳下的老洋房色调绝佳。",
    bestTime: "下午 3:00-5:30", estimatedTime: "1.5-2小时", cost: "免费",
    nearbySpots: ["意式风情区", "梁启超故居", "海河"],
    tags: ["City Walk", "摄影", "古建筑"],
    imageUrl: "https://picsum.photos/800/600?random=101",
    imageColor: "#BDB76B",
  },

  // ==================== 西北 · 西安 ====================
  {
    id: "hg-xa-1", name: "洒金桥", city: "西安", region: "西北",
    lat: 34.268, lng: 108.935,
    description: "回民街背后的真正美食秘境，本地人排队买腊牛肉、胡辣汤和甑糕。",
    reason: "比回民街正宗且便宜，西安人的私藏美食街。",
    bestTime: "早上 7:00-10:00", estimatedTime: "1-1.5小时", cost: "¥30-60/人",
    nearbySpots: ["回民街", "钟楼", "鼓楼"],
    tags: ["美食", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=102",
    imageColor: "#CD853F",
  },
  {
    id: "hg-xa-2", name: "书院门·关中书院", city: "西安", region: "西北",
    lat: 34.255, lng: 108.943,
    description: "碑林旁的古街，笔墨纸砚铺子连成排，关中书院里安静到能听见毛笔沙沙声。",
    reason: "西安最有文化气息的步行街，比城墙根更适合慢慢逛。",
    bestTime: "上午 9:00-12:00", estimatedTime: "1.5-2小时", cost: "免费",
    nearbySpots: ["碑林博物馆", "南门城墙", "钟楼"],
    tags: ["City Walk", "书店", "古建筑"],
    imageUrl: "https://picsum.photos/800/600?random=103",
    imageColor: "#8B4513",
  },
  {
    id: "hg-xa-3", name: "半坡国际艺术区", city: "西安", region: "西北",
    lat: 34.275, lng: 109.05,
    description: "老纺织厂改造的艺术区，涂鸦墙、独立设计师工作室、机车咖啡馆聚集。",
    reason: "西安最具活力的当代艺术社区，每面墙都是拍照背景。",
    bestTime: "下午 2:00-6:00", estimatedTime: "2-3小时", cost: "免费",
    nearbySpots: ["半坡遗址", "灞桥", "浐灞"],
    tags: ["艺术空间", "摄影", "咖啡馆"],
    imageUrl: "https://picsum.photos/800/600?random=104",
    imageColor: "#708090",
  },
  {
    id: "hg-xa-4", name: "大雁塔·曲江书城", city: "西安", region: "西北",
    lat: 34.21, lng: 108.96,
    description: "曲江边的两层开放式书店，落地窗外是湖水，旋转楼梯本身就是风景。",
    reason: "西安最美的书店之一，看书看累了就望窗外发发呆。",
    bestTime: "下午 2:00-6:00", estimatedTime: "1.5-2小时", cost: "免费（咖啡 ¥30-45）",
    nearbySpots: ["大雁塔", "大唐不夜城", "大唐芙蓉园"],
    tags: ["书店", "咖啡馆"],
    imageUrl: "https://picsum.photos/800/600?random=105",
    imageColor: "#4169E1",
  },

  // ==================== 西北 · 敦煌 ====================
  {
    id: "hg-dh-1", name: "敦煌夜市·沙洲食驿", city: "敦煌", region: "西北",
    lat: 40.138, lng: 94.668,
    description: "比莫高窟更接地气的敦煌体验，驴肉黄面、杏皮水和胡羊焖饼的味觉盛宴。",
    reason: "白天的敦煌属于游客，夜晚的敦煌属于美食。",
    bestTime: "晚上 7:00-10:00", estimatedTime: "1.5-2小时", cost: "¥60-100/人",
    nearbySpots: ["敦煌夜市", "党河", "反弹琵琶雕像"],
    tags: ["美食", "夜景", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=106",
    imageColor: "#DAA520",
  },
  {
    id: "hg-dh-2", name: "西千佛洞", city: "敦煌", region: "西北",
    lat: 39.98, lng: 94.37,
    description: "莫高窟的姐妹窟，游客少得多，党河崖壁上的壁画同样震撼。",
    reason: "不用排长队就能安静欣赏千年壁画，体验感完胜莫高窟。",
    bestTime: "上午 9:00-11:30", estimatedTime: "1.5-2小时", cost: "¥30",
    nearbySpots: ["莫高窟", "鸣沙山", "敦煌古城"],
    tags: ["历史文化", "小众", "摄影"],
    imageUrl: "https://picsum.photos/800/600?random=107",
    imageColor: "#D2691E",
  },
  {
    id: "hg-dh-3", name: "敦煌画院·壁画临摹", city: "敦煌", region: "西北",
    lat: 40.13, lng: 94.66,
    description: "在专业画师指导下临摹一幅敦煌壁画，用矿物颜料在泥板上还原千年色彩。",
    reason: "带走的不只是照片，而是一幅自己画的敦煌壁画。",
    bestTime: "上午 9:00-12:00", estimatedTime: "2-3小时", cost: "¥200-400/人",
    nearbySpots: ["敦煌博物馆", "沙洲夜市"],
    tags: ["非遗体验", "艺术空间"],
    imageUrl: "https://picsum.photos/800/600?random=108",
    imageColor: "#FF6347",
  },

  // ==================== 西北 · 兰州 ====================
  {
    id: "hg-lz-1", name: "白塔山·金城关", city: "兰州", region: "西北",
    lat: 36.065, lng: 103.81,
    description: "白塔山半山腰的老街区，俯瞰黄河穿城而过，傍晚时分城市灯光渐次亮起。",
    reason: "兰州的隐藏观景台，比中山桥更适合拍夜景。",
    bestTime: "傍晚 6:00-8:00", estimatedTime: "1.5-2小时", cost: "免费",
    nearbySpots: ["白塔山公园", "中山桥", "黄河母亲像"],
    tags: ["夜景", "摄影", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=109",
    imageColor: "#DAA520",
  },
  {
    id: "hg-lz-2", name: "正宁路夜市", city: "兰州", region: "西北",
    lat: 36.057, lng: 103.822,
    description: "牛奶鸡蛋醪糟排长队、烤肉烟雾缭绕、甜胚子奶茶人手一杯，西北夜生活的缩影。",
    reason: "兰州本地人认证的美食街，比大众巷更正宗。",
    bestTime: "晚上 7:00-11:00", estimatedTime: "1-1.5小时", cost: "¥40-80/人",
    nearbySpots: ["张掖路步行街", "大众巷"],
    tags: ["美食", "夜景"],
    imageUrl: "https://picsum.photos/800/600?random=110",
    imageColor: "#FF4500",
  },
  {
    id: "hg-lz-3", name: "甘肃省博物馆", city: "兰州", region: "西北",
    lat: 36.062, lng: 103.77,
    description: "马踏飞燕的真身在此，丝绸之路文明展厅是国内顶级的，铜奔马的表情包火遍全网。",
    reason: "为了马踏飞燕也值得专程来一趟，何况还有彩陶和恐龙化石。",
    bestTime: "上午 9:00-12:00", estimatedTime: "2-3小时", cost: "免费（需预约）",
    nearbySpots: ["兰州中心", "黄河风情线"],
    tags: ["博物馆", "历史文化"],
    imageUrl: "https://picsum.photos/800/600?random=111",
    imageColor: "#8B7355",
  },

  // ==================== 东北 · 哈尔滨 ====================
  {
    id: "hg-heb-1", name: "老道外·中华巴洛克", city: "哈尔滨", region: "东北",
    lat: 45.78, lng: 126.635,
    description: "中国最大的巴洛克建筑群，外墙西式内院中式，锅包肉和排骨包子的发源地。",
    reason: "哈尔滨最被低估的历史街区，建筑+美食双重享受。",
    bestTime: "上午 10:00-13:00", estimatedTime: "2-3小时", cost: "免费（美食 ¥50-80）",
    nearbySpots: ["中央大街", "圣索菲亚教堂", "松花江"],
    tags: ["古建筑", "美食", "摄影", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=112",
    imageColor: "#CD853F",
  },
  {
    id: "hg-heb-2", name: "果戈里书店", city: "哈尔滨", region: "东北",
    lat: 45.755, lng: 126.635,
    description: "哈尔滨最有腔调的独立书店，欧式装修配俄文原版书，仿佛穿越到欧洲老书店。",
    reason: "中国最美欧式书店之一，每个角落都有故事感。",
    bestTime: "下午 2:00-5:00", estimatedTime: "1.5-2小时", cost: "免费（咖啡 ¥30-50）",
    nearbySpots: ["果戈里大街", "秋林公司", "哈尔滨站"],
    tags: ["书店", "咖啡馆", "艺术空间"],
    imageUrl: "https://picsum.photos/800/600?random=113",
    imageColor: "#8B4513",
  },
  {
    id: "hg-heb-3", name: "哈尔滨大剧院", city: "哈尔滨", region: "东北",
    lat: 45.808, lng: 126.57,
    description: "MAD建筑事务所作品，被评为世界最佳建筑，湿地环绕的纯白流线型建筑。",
    reason: "即使不看演出，单是建筑本身就值得专程前往拍照。",
    bestTime: "下午 3:00-5:30", estimatedTime: "1.5-2小时", cost: "外观免费（演出另付）",
    nearbySpots: ["太阳岛", "冰雪大世界", "松北湿地"],
    tags: ["艺术空间", "摄影", "小众"],
    imageUrl: "https://picsum.photos/800/600?random=114",
    imageColor: "#F5F5F5",
  },

  // ==================== 东北 · 大连 ====================
  {
    id: "hg-dl-1", name: "渔人码头", city: "大连", region: "东北",
    lat: 38.867, lng: 121.67,
    description: "欧洲风情渔港，彩色渔船、灯塔和海鸥，旁边有很多海鲜大排档和咖啡馆。",
    reason: "大连最有异国风情的角落，拍照像在欧洲渔港。",
    bestTime: "下午 3:00-6:00", estimatedTime: "1.5-2小时", cost: "免费（海鲜 ¥80-150）",
    nearbySpots: ["老虎滩", "棒棰岛", "滨海路"],
    tags: ["摄影", "美食", "海边"],
    imageUrl: "https://picsum.photos/800/600?random=115",
    imageColor: "#4682B4",
  },
  {
    id: "hg-dl-2", name: "南山风情街", city: "大连", region: "东北",
    lat: 38.905, lng: 121.638,
    description: "日式老别墅改造的咖啡馆和设计店，每条小巷子都通向一个小惊喜。",
    reason: "大连最文艺的街区，适合没有目的地随便走走。",
    bestTime: "下午 2:00-5:00", estimatedTime: "1.5-2小时", cost: "免费（咖啡 ¥30-50）",
    nearbySpots: ["中山广场", "友好广场", "青泥洼桥"],
    tags: ["City Walk", "咖啡馆", "摄影"],
    imageUrl: "https://picsum.photos/800/600?random=116",
    imageColor: "#6B8E23",
  },
  {
    id: "hg-dl-3", name: "旅顺·太阳沟", city: "大连", region: "东北",
    lat: 38.81, lng: 121.25,
    description: "百年历史街区，秋天的银杏大道金黄一片，老建筑群保存完好，时间仿佛停住。",
    reason: "大连最有历史厚重感的地方，秋天来美到词穷。",
    bestTime: "10-11月（全天）", estimatedTime: "2-3小时", cost: "免费",
    nearbySpots: ["旅顺博物馆", "白玉山", "军港"],
    tags: ["摄影", "历史文化", "City Walk"],
    imageUrl: "https://picsum.photos/800/600?random=117",
    imageColor: "#DAA520",
  },
];

// 按城市聚合
export function getGemsByCity(city: string): GemSpot[] {
  return allHiddenGems.filter((g) => g.city === city);
}

// 按标签筛选
export function getGemsByTag(tag: string): GemSpot[] {
  return allHiddenGems.filter((g) => g.tags.includes(tag));
}

// 获取所有城市列表
export function getGemCities(): string[] {
  return [...new Set(allHiddenGems.map((g) => g.city))];
}
